repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
-   repo: local
    hooks:
    - id: documentation
      name: gendoc
      entry: ./scripts/documentation/generate_template_doc.py
      language: python
