repos:
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.7.0
    hooks:
    - id: isort

-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.9

-   repo: local
    hooks:
    - id: django-migrations
      name: check for missing migrations
      entry: ./manage.py makemigrations --check
      language: system
      types: [python]
      pass_filenames: false
